sudo: required
services: 
  - docker
before_install:
  - docker build -t vivek.goel/frontend .
script: 
  - docker run vivek.goel/frontend npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-774939556611"
  bucket_path: "docker-frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

